// Indonesian stopwords
export class StopwordRemover {
  private stopwords: Set<string>;

  constructor() {
    this.stopwords = new Set([
      'yang', 'untuk', 'pada', 'ke', 'para', 'namun', 'menurut', 'antara', 'dia', 'dua',
      'ia', 'seperti', 'jika', 'jadi', 'maka', 'ketika', 'sebagai', 'ini', 'itu', 'tersebut',
      'dalam', 'dari', 'dan', 'di', 'dengan', 'adalah', 'akan', 'atau', 'ada', 'dapat',
      'telah', 'sudah', 'oleh', 'bisa', 'hal', 'kami', 'mereka', 'kita', 'saya', 'anda',
      'juga', 'saat', 'lebih', 'sangat', 'harus', 'belum', 'tidak', 'bukan', 'masih',
      'setiap', 'karena', 'hingga', 'hanya', 'agar', 'pun', 'pula', 'serta', 'maupun',
      'sedangkan', 'padahal', 'walaupun', 'meskipun', 'ataupun', 'bahwa', 'oleh', 'secara',
      'nya', 'nih', 'lho', 'loh', 'dong', 'sih', 'deh', 'kok', 'yah', 'dg', 'dgn', 'utk',
      'pd', 'kpd', 'krn', 'tsb', 'dll', 'dsb', 'dst', 'yg', 'sb', 'sbg', 'spt', 'jk',
      'kl', 'jd', 'mk', 'kt', 'an', 'ku', 'mu', 'kah', 'lah', 'tah',
      'per', 'bagi', 'beliau', 'berikut', 'berupa', 'bilion', 'bisakah', 'boleh', 'bolehkah',
      'bung', 'cara', 'caranya', 'cukup', 'cukupkah', 'dahulu', 'demi', 'dimana', 'dimanapun',
      'dimulai', 'disebutkan', 'ditegaskan', 'ditunjuk', 'ditunjuki', 'ditunjukkan', 'ditunjukkannya',
      'empat', 'enggak', 'enggaknya', 'entah', 'guna', 'gunakan', 'hampir',
      'hanyalah', 'haruslah', 'harusnya', 'hendak', 'hendaklah', 'hendaknya',
      'http', 'ibaratnya', 'ikut', 'ingat', 'ingin', 'inginkan',
      'inikah', 'itukah', 'itulah', 'jangan', 'jangankan', 'janganlah',
      'jumlah', 'jumlahnya', 'justru', 'kadang', 'kadangkala', 'kalau', 'kalaulah', 'kalaupun',
      'kamulah', 'kan', 'kapan', 'kapankah', 'kapanpun', 'karenanya', 'kasus',
      'kata', 'katakan', 'katakanlah', 'katanya', 'keadaan', 'kebetulan', 'kecil',
      'kedua', 'keduanya', 'kelak', 'kelima', 'kemarin', 'kemudian', 'kemungkinan', 'kemungkinannya',
      'kenapa', 'kepada', 'kepadanya', 'kesampaian', 'keseluruhan', 'keseluruhannya', 'keterlaluan',
      'khususnya', 'kini', 'kinilah', 'kira', 'kiranya', 'kitalah',
      'lagi', 'lagian', 'lain', 'lainnya', 'lalu', 'lama', 'lamanya', 'lanjut',
      'lanjutnya', 'lewat', 'lima', 'luar', 'makanya', 'makin', 'malah',
      'malahan', 'mampu', 'mampukah', 'mana', 'manakala', 'manalagi', 'masa', 'masalah',
      'masalahnya', 'masing', 'mau', 'melainkan', 'melakukan',
      'melalui', 'melihat', 'melihatnya', 'memang', 'memastikan', 'memberi', 'memberikan',
      'meminta', 'memintakan', 'memisalkan', 'memperbuat', 'mempergunakan', 'memperkirakan',
      'memperlihatkan', 'mempersiapkan', 'mempersoalkan', 'mempertanyakan', 'mempunyai',
      'memungkinkan', 'menaiki', 'menambahkan', 'menandaskan', 'menanti',
      'menantikan', 'menanya', 'menanyai', 'menanyakan', 'mendapat', 'mendapatkan', 'mendatang',
      'mendatangi', 'mendatangkan', 'menegaskan', 'mengakhiri', 'mengapa', 'mengatakan',
      'mengatakannya', 'mengenai', 'mengerjakan', 'mengetahui', 'menggunakan', 'menghendaki',
      'mengibaratkan', 'mengibaratkannya', 'mengingat', 'mengingatkan', 'menginginkan',
      'mengira', 'mengucapkan', 'mengucapkannya', 'mengungkapkan', 'menjadi', 'menjawab',
      'menjelaskan', 'menuju', 'menunjuk', 'menunjuki', 'menunjukkan', 'menunjuknya',
      'menuturkan', 'menyampaikan', 'menyangkut', 'menyatakan', 'menyebutkan',
      'menyeluruh', 'menyiapkan', 'merasa', 'merekalah', 'merupakan', 'meski',
      'meyakini', 'meyakinkan', 'minta', 'mirip', 'misal', 'misalkan', 'misalnya',
      'mula', 'mulai', 'mulailah', 'mulanya', 'mungkin', 'mungkinkah', 'nah', 'naik', 'nanti',
      'nantinya', 'nyaris', 'olehnya', 'padahal', 'padanya',
      'pak', 'paling', 'panjang', 'pantas', 'pasti', 'pastilah', 'penting', 'pentingnya',
      'percuma', 'pergunakan', 'perlukah', 'perlu', 'pernah', 'persoalan', 'pertama',
      'pertanyaan', 'pertanyakan', 'pihak', 'pihaknya', 'pukul', 'pula', 'punya', 'rasa',
      'rasanya', 'rata', 'rupanya', 'saatnya', 'saja', 'sajalah', 'saling', 'sama',
      'sambil', 'sampai', 'sampaikan', 'sana', 'sangatlah',
      'se', 'sebab', 'sebabnya', 'sebagaimana', 'sebagainya',
      'sebagian', 'sebaik', 'sebaiknya', 'sebaliknya', 'sebanyak', 'sebegini',
      'sebegitu', 'sebelum', 'sebelumnya', 'sebenarnya', 'seberapa', 'sebesar', 'sebetulnya',
      'sebisanya', 'sebuah', 'sebut', 'sebutlah', 'sebutnya', 'secukupnya', 'sedang',
      'sedemikian', 'sedikit', 'sedikitnya', 'seenaknya', 'segala', 'segalanya',
      'segera', 'seharusnya', 'sehingga', 'seingat', 'sejak', 'sejauh', 'sejenak', 'sejumlah',
      'sekadar', 'sekadarnya', 'sekali', 'sekalian', 'sekaligus', 'sekalipun',
      'sekarang', 'sekecil', 'seketika', 'sekiranya', 'sekitar', 'sekitarnya',
      'sekurangnya', 'sela', 'selain', 'selaku', 'selalu', 'selama',
      'selamanya', 'selanjutnya', 'seluruh', 'seluruhnya', 'semacam', 'semakin',
      'semampu', 'semampunya', 'semasa', 'semasih', 'semata', 'semaunya', 'sementara',
      'semua', 'semuanya', 'semula', 'sendiri', 'sendirian', 'sendirinya', 'seolah',
      'seorang', 'sepanjang', 'sepantasnya', 'sepantasnyalah', 'seperlunya', 'seperti', 'sepertinya',
      'sepihak', 'sering', 'seringnya', 'serupa', 'sesaat', 'sesama', 'sesampai', 'sesegera',
      'sesekali', 'seseorang', 'sesuatu', 'sesuatunya', 'sesudah', 'sesudahnya', 'setelah', 'setelahnya',
      'setempat', 'setengah', 'seterusnya', 'setiba', 'setibanya',
      'setidaknya', 'setinggi', 'seusai', 'sewaktu', 'siap', 'siapa', 'siapakah', 'siapapun', 'sini',
      'sinilah', 'soal', 'soalnya', 'suatu', 'sudahkah', 'sudahlah', 'supaya', 'tadi',
      'tadinya', 'tahu', 'tahun', 'tak', 'tambah', 'tambahnya', 'tampak', 'tampaknya', 'tandas',
      'tandasnya', 'tanpa', 'tanya', 'tanyakan', 'tanyanya', 'tapi', 'tegas', 'tegasnya',
      'tempat', 'tengah', 'tentang', 'tentulah', 'tentunya', 'tepat', 'terakhir', 'terasa', 'terbanyak',
      'terdahulu', 'terdapat', 'terdiri', 'terhadap', 'terhadapnya', 'teringat',
      'terjadi', 'terjadilah', 'terjadinya', 'terkira', 'terlalu', 'terlebih', 'terlihat', 'termasuk',
      'ternyata', 'tersampaikan', 'tersebutlah', 'tertentu', 'tertuju', 'terus', 'terutama',
      'tetap', 'tetapi', 'tiap', 'tiba', 'tidak', 'tidakkah', 'tidaklah', 'tiga', 'tinggi',
      'toh', 'tunjuk', 'turut', 'tutur', 'tuturnya', 'ucap', 'ucapnya', 'ujar', 'ujarnya', 'umum',
      'umumnya', 'ungkap', 'ungkapnya', 'usah', 'usai', 'waduh', 'wah', 'wahai', 'waktu',
      'waktunya', 'walau', 'walaupun', 'wong', 'yaitu', 'yakni', 'yakin', 'adapun',
    ]);
  }

  removeStopwords(tokens: string[]): string[] {
    return tokens.filter(token => !this.stopwords.has(token));
  }
}
